# Generated by Django 3.0.6 on 2020-05-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('sm', 'Small'), ('lr', 'Large')], default='sm', max_length=2)),
                ('crust', models.CharField(choices=[('re', 'Regular Crust'), ('sc', 'Sicilian Crust')], default='re', max_length=2)),
                ('topping_type', models.CharField(choices=[('ch', 'Cheese'), ('1t', '1 Topping'), ('2t', '2 Topping'), ('3t', '3 Topping'), ('4t', '4 Topping'), ('5t', '5 Topping'), ('sp', 'Special')], default='ch', max_length=2)),
            ],
        ),
    ]
