# Generated by Django 3.0.6 on 2020-05-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='topping_type',
            field=models.CharField(choices=[('ch', 'Cheese'), ('1t', '1 Topping'), ('2t', '2 Topping'), ('3t', '3 Topping'), ('sp', 'Special')], default='ch', max_length=2),
        ),
    ]
