# Generated by Django 3.0.6 on 2020-05-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_dinner_order_order_pizza_order_sub_order_subs'),
    ]

    operations = [
        migrations.CreateModel(
            name='dinner_plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('sm', 'Small'), ('lr', 'Large')], default='sm', max_length=2)),
                ('name', models.CharField(choices=[('gas', 'Garden Salad'), ('grs', 'Greek Salad'), ('apo', 'Antipasto'), ('bkz', 'Baked Ziti'), ('mbp', 'Meatball Parm'), ('ckp', 'Chicken Parm')], default='gas', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bzmo', 'Baked Ziti w/Mozzarella'), ('bzme', 'Baked Ziti w/Meatballs'), ('bzch', 'Baked Ziti w/Chicken')], default='bzmo', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('gas', 'Garden Salad'), ('grs', 'Greek Salad'), ('apo', 'Antipasto'), ('swt', 'Salad w/Tuna')], default='gas', max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='dinner_order',
        ),
    ]
