# Generated by Django 3.0.6 on 2020-05-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200508_1925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paste',
            new_name='pasta',
        ),
    ]
