# Generated by Django 3.0.6 on 2020-05-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200508_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_order',
            name='pizzas',
            field=models.ManyToManyField(to='orders.pizza'),
        ),
        migrations.AddField(
            model_name='pizza_order',
            name='toppings',
            field=models.ManyToManyField(to='orders.topping'),
        ),
    ]
